version: "3"
services:
  hubot:
    container_name: hubot
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    environment:
      - HUBOT_SLACK_TOKEN=xxxxx
      - HUBOT_NAME=homebot
