version: "3"
services:
  hubot:
    container_name: hubot
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    environment:
      - HUBOT_SLACK_TOKEN=xxxxx
      - EXTERNAL_SCRIPTS=hubot-broadlink-rm
  pigpiod:
    container_name: pigpiod
    image: corbosman/pigpiod
    restart: always
    privileged: true
